version: '3.4'

services:
  # @TODO: To be used instead of the current tests orchestration (with fake server), coming soon...
  tests:
    build:
      context: ../../
      dockerfile: .divido/docker/Dockerfile
      target: test
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    container_name: ${SERVICE_NAME}-tests
    command: /bin/sh -c "bin/phpunit --stop-on-failure --coverage-text=/opt/divido/app/tmp/coverage.out"
    volumes:
      - ../../:/opt/divido/app

networks:
  default:
    external:
      name: ${NETWORK}
