version: '3'
services:

  divido-application-api-rpc:
    container_name: divido-application-api-rpc
    build:
          context: ""
          dockerfile: rpc/Dockerfile
    volumes:
      - ../../../:/opt/divido/app
    environment:
      - DIVIDO_APPLICATION_ENVIRONMENT=development
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

networks:
  default:
    external:
      name: environment_divido-environment-platform